---
title: "262 first day of class homework - about me!"
author: "Evan Heberlein"
date: "2/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


I am taking 262 to improve my coding skills and understanding of coding principles - hopefully making it a more intuitive part of my skillset. One of the most attractive things about Bren is the EDS focus. Gaining more basic computing skills that are applicable outside of environmental work is one of my goals to make EDS more marketable and valueable after graduating. I hope we can start from a very fundamental level, because my background in writing programs is very disjointed and I want to rebuild my base.

During undergrad, I took a statistics class in R and audited a computer programming class in Python. I have also used Excel extensively, and I am competent at producing figures in ArcGIS (I have used GIS for work previously and am taking 262 right now). Allison's 206 class was my first formal introduction to data science as a discipline and I will take 241 next year. I understand Python/R script but am not very competent in developing unique ideas/approaches in code, and hope to get more guidance in this course.
